name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"

      - name: Install dependencies
        working-directory: ./api1
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask API in the background
        working-directory: ./api1
        run: |
          python app.py &
          echo "Flask API running in the background"

      - name: Wait for Flask to start
        run: sleep 10  # Attendre que l'API démarre

      - name: Test the Classification API
        working-directory: ./api1
        run: |
          curl --request POST http://127.0.0.1:5000/predict/classification \
          --header "Content-Type: application/json" \
          --data '{
              "features": {
                "Year": 2024,
                "Month": 12,
                "Day": 3,
                "Author": "${{ env.COMMIT_AUTHOR }}",
                "message": "${{ env.COMMIT_MESSAGE }}",
                "modified_files": "${{ env.MODIFIED_FILES }}",
                "functions": "test_function1 test_function2"
              }
            }'
